config/routes.rb
Rails.application.routes.draw do

  root to: 'assignments#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions',
    passwords: 'students/passwords'
  }

  resources :assignments, only: [:index, :show] do
    resources :ranks, only: [:index, :new, :create] 
  end

  resources :ranks, only: :show
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    has_many :ranks
    has_and_belongs_to_many :students
    has_many :assignments_students

    enum status: [:inactive, :active]
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    before_action :authenticate_student!, only: [:index]
    before_action :authenticate_admin_user!, only: [:show]

    def index
        @assignments = current_student.assignments
    end

    def show
        teams = Team.all
        ranks = Rank.where(assignment_id: params[:id]).joins(:students).joins(:ranks)
        assignment = Assignment.find(params[:id])
        teams.each do |team|
        team.students.each do |student|
            AssignmentsStudent.calculate_score(student.id, assignment.id)
        end
        team = team.calculate_team_average(assignment.id)
        end
        redirect_to admin_assignment_path(assignment.id)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/index.html.haml
%div.row
    %div.col-md-12
        %h2.text-center Peer Rating of Team Members
        %h3.text-center Please click on the button on the corresponding row of the assignment to get started.
        %table.table.table-responsive-md.table-striped
            %thead
                %tr
                    %th Name
                    %th Status
                    %th Action
            %tbody
                - @assignments.each do |assignment|
                    - if assignment.active?
                        %tr
                            %td= assignment.name
                            - if current_student.has_already_ranked_for(assignment.id)
                                %td
                                    %span.badge.badge-success Done
                                %td No action required
                            - else
                                %td
                                    %span.badge.badge-warning Pending
                                %td= button_to "Rate", new_assignment_rank_path(assignment.id), method: :get, class: 'btn btn-primary', data: { turbolinks: false }
        = button_to "Log out", destroy_student_session_path, method: :delete, class: 'btn btn-danger', data: { turbolinks: false }
                        