config/routes.rb
Rails.application.routes.draw do

  root to: 'assignments#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions',
    passwords: 'students/passwords'
  }

  resources :assignments, only: [:index, :show] do
    resources :ranks, only: [:index, :new, :create] 
  end

  resources :ranks, only: :show
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    has_many :ranks
    has_and_belongs_to_many :students
    has_many :assignments_students

    enum status: [:inactive, :active]
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    before_action :authenticate_student!, only: [:index]
    before_action :authenticate_admin_user!, only: [:show]

    def index
        @assignments = current_student.assignments
    end

    def show
        teams = Team.all
        ranks = Rank.where(assignment_id: params[:id]).joins(:students).joins(:ranks)
        assignment = Assignment.find(params[:id])
        teams.each do |team|
        team.students.each do |student|
            AssignmentsStudent.calculate_score(student.id, assignment.id)
        end
        team = team.calculate_team_average(assignment.id)
        end
        redirect_to admin_assignment_path(assignment.id)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/admin/assignments/_teams.html.haml
= button_to "Recalculate Scores", assignment_path(assignment.id), method: :get, class: "btn btn-primary"
%br
= button_to "Export to CSV", rank_path(assignment.id, format: "csv"), method: :get, class: "btn btn-success"
%br
#accordion.panel-group
    -teams.each do |team|
        .panel.panel-default
            .panel-heading
                %h4.panel-title
                %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse#{team.team_id}"}
                    %h4= team.team_name
            %div{id: "collapse#{team.team_id}", class: "panel-collapse collapse"}
                .panel-body
                    %table.table.table-responsive-md.table-striped
                        %thead
                            %tr
                                %th Student Id
                                %th Student Name
                                - for i in 1..team.students.length()
                                    %th= "Vote #{i}"
                                %th Individual Avgerage
                                %th Team Average
                                %th Adj Factor Cap
                                %th Individual Project Grade
                                %th Adj. Fctr.
                                %th Team Grade
                                %th Individual Grade
                                
                        %tbody
                            - team.students.each do |student|
                                %tr
                                    %td= student.student_id
                                    %td= student.name
                                    - student.received_ranks.where(assignment_id: assignment.id).each do |rank|
                                        %td= rank.rating.humanize
                                    - for i in 1..(team.students.length() - student.received_ranks.where(assignment_id: assignment.id).length())
                                        %td= "N/A"
                                    %td= assignment.assignments_students.find_by(student_id: student.id).individual_average
                                    %td= team.team_average
                                    %td= assignment.adjustment_factor_cap
                                    %td= assignment.assignments_students.find_by(student_id: student.id).individual_project_grade
                                    %td= assignment.assignments_students.find_by(student_id: student.id).adjustment_factor
                                    %td= team.team_grade
                                    %td= assignment.assignments_students.find_by(student_id: student.id).individual_grade
                        
                    - if (team.students.length() - team.students.first.received_ranks.where(assignment_id: assignment.id).length()) > 0
                        %h4 Students yet to submit peer review
                        %table.table.table-responsive-md.table-striped
                            %thead
                                %tr 
                                    %th Student Id
                                    %th Student name
                                    %th Email
                            %tbody
                                - team.students.each do |student|
                                    - if student.has_not_ranked_for(assignment.id)
                                        %tr 
                                            %td= student.student_id
                                            %td= student.name
                                            %td= student.email
                    - else
                        %h4 All students from this group have submitted peer review
                            
                
                    